### ISSUE TITLE
Missing parameter type for 'e'.  Try adding an explicit type, or remove implicit-dynamic from your analysis options file.

### ISSUE THREAD

**Issue by tenSunFree** [hukusuke1007/flutter_app_template#35]
Missing parameter type for 'e'.  Try adding an explicit type, or remove implicit-dynamic from your analysis options file.
![001](https://user-images.githubusercontent.com/23090085/203366800-d89693de-5434-4bf1-931a-b9294556c30e.jpg)

Maybe consider adding a dynamic type.
![002](https://user-images.githubusercontent.com/23090085/203367102-5fa431e9-9fa1-4705-9687-9f999f9c43f3.jpg)

Cascade consecutive method invocations on the same reference. (Documentation) 
![003](https://user-images.githubusercontent.com/23090085/203367163-2d2dc82b-195f-466a-a8f0-d97f5f9ef595.jpg)

Maybe consider using a cascade operator.
![004](https://user-images.githubusercontent.com/23090085/203367454-7b160c61-1451-419d-89ca-ca8138d45594.jpg)

**Comment by hukusuke1007** [comment]
It is an auto-generated file and I cannot modify it. So *.g.dart files is excluded in analysis_options.yaml. 

https://github.com/hukusuke1007/flutter_app_template/blob/main/analysis_options.yaml
