### ISSUE TITLE
Set _lastUserId to be nullable

### ISSUE THREAD

**Issue by tenSunFree** [hukusuke1007/flutter_app_template#36]
I'm a little curious.
Is it redundant to set _lastUserId to be empty?
![2022-11-24_003118](https://user-images.githubusercontent.com/23090085/203601161-9ba218af-1d28-4e94-9db5-ce5682012450.jpg)

Because I didn’t see the relevant judgment you made when _lastUserId was empty.
In the fetch() part, I also saw that you set 0 for _lastUserId, make sure _lastUserId is not empty.
So since _lastUserId is up to us to decide whether it is empty or not, and there is no related use when it is empty, why not set _lastUserId not to be empty from the beginning?
![2022-11-24_004222](https://user-images.githubusercontent.com/23090085/203601736-ea3f432f-4269-4696-b33c-0ffa5ae61f7a.jpg)

**Comment by hukusuke1007** [comment]
ok
